function __omniwmctl_prev_arg_is
    set -l tokens (commandline -opc)
    test (count $tokens) -gt 0; or return 1
    set -l prev $tokens[-1]
    contains -- $prev $argv
end
complete -c omniwmctl -f -n '__fish_use_subcommand' -a 'ping'
complete -c omniwmctl -f -n '__fish_use_subcommand' -a 'version'
complete -c omniwmctl -f -n '__fish_use_subcommand' -a 'help'
complete -c omniwmctl -f -n '__fish_use_subcommand' -a 'completion'
complete -c omniwmctl -f -n '__fish_use_subcommand' -a 'command'
complete -c omniwmctl -f -n '__fish_use_subcommand' -a 'query'
complete -c omniwmctl -f -n '__fish_use_subcommand' -a 'rule'
complete -c omniwmctl -f -n '__fish_use_subcommand' -a 'workspace'
complete -c omniwmctl -f -n '__fish_use_subcommand' -a 'window'
complete -c omniwmctl -f -n '__fish_use_subcommand' -a 'subscribe'
complete -c omniwmctl -f -n '__fish_use_subcommand' -a 'watch'
complete -c omniwmctl -f -n '__fish_seen_subcommand_from query' -a 'active-workspace'
complete -c omniwmctl -f -n '__fish_seen_subcommand_from query' -a 'apps'
complete -c omniwmctl -f -n '__fish_seen_subcommand_from query' -a 'capabilities'
complete -c omniwmctl -f -n '__fish_seen_subcommand_from query' -a 'commands'
complete -c omniwmctl -f -n '__fish_seen_subcommand_from query' -a 'displays'
complete -c omniwmctl -f -n '__fish_seen_subcommand_from query' -a 'focused-monitor'
complete -c omniwmctl -f -n '__fish_seen_subcommand_from query' -a 'focused-window'
complete -c omniwmctl -f -n '__fish_seen_subcommand_from query' -a 'focused-window-decision'
complete -c omniwmctl -f -n '__fish_seen_subcommand_from query' -a 'monitors'
complete -c omniwmctl -f -n '__fish_seen_subcommand_from query' -a 'queries'
complete -c omniwmctl -f -n '__fish_seen_subcommand_from query' -a 'rule-actions'
complete -c omniwmctl -f -n '__fish_seen_subcommand_from query' -a 'rules'
complete -c omniwmctl -f -n '__fish_seen_subcommand_from query' -a 'subscriptions'
complete -c omniwmctl -f -n '__fish_seen_subcommand_from query' -a 'windows'
complete -c omniwmctl -f -n '__fish_seen_subcommand_from query' -a 'workspace-bar'
complete -c omniwmctl -f -n '__fish_seen_subcommand_from query' -a 'workspaces'
complete -c omniwmctl -f -n '__fish_seen_subcommand_from query; and __fish_seen_subcommand_from displays' -a '--current'
complete -c omniwmctl -f -n '__fish_seen_subcommand_from query; and __fish_seen_subcommand_from displays' -a '--display'
complete -c omniwmctl -f -n '__fish_seen_subcommand_from query; and __fish_seen_subcommand_from displays' -a '--fields'
complete -c omniwmctl -f -n '__fish_seen_subcommand_from query; and __fish_seen_subcommand_from displays' -a '--main'
complete -c omniwmctl -f -n '__fish_seen_subcommand_from query; and __fish_seen_subcommand_from displays' -a '--monitor'
complete -c omniwmctl -f -n '__fish_seen_subcommand_from query; and __fish_seen_subcommand_from monitors' -a '--current'
complete -c omniwmctl -f -n '__fish_seen_subcommand_from query; and __fish_seen_subcommand_from monitors' -a '--display'
complete -c omniwmctl -f -n '__fish_seen_subcommand_from query; and __fish_seen_subcommand_from monitors' -a '--fields'
complete -c omniwmctl -f -n '__fish_seen_subcommand_from query; and __fish_seen_subcommand_from monitors' -a '--main'
complete -c omniwmctl -f -n '__fish_seen_subcommand_from query; and __fish_seen_subcommand_from monitors' -a '--monitor'
complete -c omniwmctl -f -n '__fish_seen_subcommand_from query; and __fish_seen_subcommand_from windows' -a '--app'
complete -c omniwmctl -f -n '__fish_seen_subcommand_from query; and __fish_seen_subcommand_from windows' -a '--bundle-id'
complete -c omniwmctl -f -n '__fish_seen_subcommand_from query; and __fish_seen_subcommand_from windows' -a '--display'
complete -c omniwmctl -f -n '__fish_seen_subcommand_from query; and __fish_seen_subcommand_from windows' -a '--fields'
complete -c omniwmctl -f -n '__fish_seen_subcommand_from query; and __fish_seen_subcommand_from windows' -a '--floating'
complete -c omniwmctl -f -n '__fish_seen_subcommand_from query; and __fish_seen_subcommand_from windows' -a '--focused'
complete -c omniwmctl -f -n '__fish_seen_subcommand_from query; and __fish_seen_subcommand_from windows' -a '--monitor'
complete -c omniwmctl -f -n '__fish_seen_subcommand_from query; and __fish_seen_subcommand_from windows' -a '--scratchpad'
complete -c omniwmctl -f -n '__fish_seen_subcommand_from query; and __fish_seen_subcommand_from windows' -a '--visible'
complete -c omniwmctl -f -n '__fish_seen_subcommand_from query; and __fish_seen_subcommand_from windows' -a '--window'
complete -c omniwmctl -f -n '__fish_seen_subcommand_from query; and __fish_seen_subcommand_from windows' -a '--workspace'
complete -c omniwmctl -f -n '__fish_seen_subcommand_from query; and __fish_seen_subcommand_from workspaces' -a '--current'
complete -c omniwmctl -f -n '__fish_seen_subcommand_from query; and __fish_seen_subcommand_from workspaces' -a '--display'
complete -c omniwmctl -f -n '__fish_seen_subcommand_from query; and __fish_seen_subcommand_from workspaces' -a '--fields'
complete -c omniwmctl -f -n '__fish_seen_subcommand_from query; and __fish_seen_subcommand_from workspaces' -a '--focused'
complete -c omniwmctl -f -n '__fish_seen_subcommand_from query; and __fish_seen_subcommand_from workspaces' -a '--monitor'
complete -c omniwmctl -f -n '__fish_seen_subcommand_from query; and __fish_seen_subcommand_from workspaces' -a '--visible'
complete -c omniwmctl -f -n '__fish_seen_subcommand_from query; and __fish_seen_subcommand_from workspaces' -a '--workspace'
complete -c omniwmctl -f -n '__fish_seen_subcommand_from query; and __fish_seen_subcommand_from displays; and __omniwmctl_prev_arg_is --fields' -a 'active-workspace'
complete -c omniwmctl -f -n '__fish_seen_subcommand_from query; and __fish_seen_subcommand_from displays; and __omniwmctl_prev_arg_is --fields' -a 'frame'
complete -c omniwmctl -f -n '__fish_seen_subcommand_from query; and __fish_seen_subcommand_from displays; and __omniwmctl_prev_arg_is --fields' -a 'has-notch'
complete -c omniwmctl -f -n '__fish_seen_subcommand_from query; and __fish_seen_subcommand_from displays; and __omniwmctl_prev_arg_is --fields' -a 'id'
complete -c omniwmctl -f -n '__fish_seen_subcommand_from query; and __fish_seen_subcommand_from displays; and __omniwmctl_prev_arg_is --fields' -a 'is-current'
complete -c omniwmctl -f -n '__fish_seen_subcommand_from query; and __fish_seen_subcommand_from displays; and __omniwmctl_prev_arg_is --fields' -a 'is-main'
complete -c omniwmctl -f -n '__fish_seen_subcommand_from query; and __fish_seen_subcommand_from displays; and __omniwmctl_prev_arg_is --fields' -a 'name'
complete -c omniwmctl -f -n '__fish_seen_subcommand_from query; and __fish_seen_subcommand_from displays; and __omniwmctl_prev_arg_is --fields' -a 'orientation'
complete -c omniwmctl -f -n '__fish_seen_subcommand_from query; and __fish_seen_subcommand_from displays; and __omniwmctl_prev_arg_is --fields' -a 'visible-frame'
complete -c omniwmctl -f -n '__fish_seen_subcommand_from query; and __fish_seen_subcommand_from monitors; and __omniwmctl_prev_arg_is --fields' -a 'active-workspace'
complete -c omniwmctl -f -n '__fish_seen_subcommand_from query; and __fish_seen_subcommand_from monitors; and __omniwmctl_prev_arg_is --fields' -a 'frame'
complete -c omniwmctl -f -n '__fish_seen_subcommand_from query; and __fish_seen_subcommand_from monitors; and __omniwmctl_prev_arg_is --fields' -a 'has-notch'
complete -c omniwmctl -f -n '__fish_seen_subcommand_from query; and __fish_seen_subcommand_from monitors; and __omniwmctl_prev_arg_is --fields' -a 'id'
complete -c omniwmctl -f -n '__fish_seen_subcommand_from query; and __fish_seen_subcommand_from monitors; and __omniwmctl_prev_arg_is --fields' -a 'is-current'
complete -c omniwmctl -f -n '__fish_seen_subcommand_from query; and __fish_seen_subcommand_from monitors; and __omniwmctl_prev_arg_is --fields' -a 'is-main'
complete -c omniwmctl -f -n '__fish_seen_subcommand_from query; and __fish_seen_subcommand_from monitors; and __omniwmctl_prev_arg_is --fields' -a 'name'
complete -c omniwmctl -f -n '__fish_seen_subcommand_from query; and __fish_seen_subcommand_from monitors; and __omniwmctl_prev_arg_is --fields' -a 'orientation'
complete -c omniwmctl -f -n '__fish_seen_subcommand_from query; and __fish_seen_subcommand_from monitors; and __omniwmctl_prev_arg_is --fields' -a 'visible-frame'
complete -c omniwmctl -f -n '__fish_seen_subcommand_from query; and __fish_seen_subcommand_from windows; and __omniwmctl_prev_arg_is --fields' -a 'app'
complete -c omniwmctl -f -n '__fish_seen_subcommand_from query; and __fish_seen_subcommand_from windows; and __omniwmctl_prev_arg_is --fields' -a 'display'
complete -c omniwmctl -f -n '__fish_seen_subcommand_from query; and __fish_seen_subcommand_from windows; and __omniwmctl_prev_arg_is --fields' -a 'frame'
complete -c omniwmctl -f -n '__fish_seen_subcommand_from query; and __fish_seen_subcommand_from windows; and __omniwmctl_prev_arg_is --fields' -a 'hidden-reason'
complete -c omniwmctl -f -n '__fish_seen_subcommand_from query; and __fish_seen_subcommand_from windows; and __omniwmctl_prev_arg_is --fields' -a 'id'
complete -c omniwmctl -f -n '__fish_seen_subcommand_from query; and __fish_seen_subcommand_from windows; and __omniwmctl_prev_arg_is --fields' -a 'is-focused'
complete -c omniwmctl -f -n '__fish_seen_subcommand_from query; and __fish_seen_subcommand_from windows; and __omniwmctl_prev_arg_is --fields' -a 'is-scratchpad'
complete -c omniwmctl -f -n '__fish_seen_subcommand_from query; and __fish_seen_subcommand_from windows; and __omniwmctl_prev_arg_is --fields' -a 'is-visible'
complete -c omniwmctl -f -n '__fish_seen_subcommand_from query; and __fish_seen_subcommand_from windows; and __omniwmctl_prev_arg_is --fields' -a 'layout-reason'
complete -c omniwmctl -f -n '__fish_seen_subcommand_from query; and __fish_seen_subcommand_from windows; and __omniwmctl_prev_arg_is --fields' -a 'manual-override'
complete -c omniwmctl -f -n '__fish_seen_subcommand_from query; and __fish_seen_subcommand_from windows; and __omniwmctl_prev_arg_is --fields' -a 'mode'
complete -c omniwmctl -f -n '__fish_seen_subcommand_from query; and __fish_seen_subcommand_from windows; and __omniwmctl_prev_arg_is --fields' -a 'pid'
complete -c omniwmctl -f -n '__fish_seen_subcommand_from query; and __fish_seen_subcommand_from windows; and __omniwmctl_prev_arg_is --fields' -a 'title'
complete -c omniwmctl -f -n '__fish_seen_subcommand_from query; and __fish_seen_subcommand_from windows; and __omniwmctl_prev_arg_is --fields' -a 'workspace'
complete -c omniwmctl -f -n '__fish_seen_subcommand_from query; and __fish_seen_subcommand_from workspaces; and __omniwmctl_prev_arg_is --fields' -a 'display'
complete -c omniwmctl -f -n '__fish_seen_subcommand_from query; and __fish_seen_subcommand_from workspaces; and __omniwmctl_prev_arg_is --fields' -a 'display-name'
complete -c omniwmctl -f -n '__fish_seen_subcommand_from query; and __fish_seen_subcommand_from workspaces; and __omniwmctl_prev_arg_is --fields' -a 'focused-window-id'
complete -c omniwmctl -f -n '__fish_seen_subcommand_from query; and __fish_seen_subcommand_from workspaces; and __omniwmctl_prev_arg_is --fields' -a 'id'
complete -c omniwmctl -f -n '__fish_seen_subcommand_from query; and __fish_seen_subcommand_from workspaces; and __omniwmctl_prev_arg_is --fields' -a 'is-current'
complete -c omniwmctl -f -n '__fish_seen_subcommand_from query; and __fish_seen_subcommand_from workspaces; and __omniwmctl_prev_arg_is --fields' -a 'is-focused'
complete -c omniwmctl -f -n '__fish_seen_subcommand_from query; and __fish_seen_subcommand_from workspaces; and __omniwmctl_prev_arg_is --fields' -a 'is-visible'
complete -c omniwmctl -f -n '__fish_seen_subcommand_from query; and __fish_seen_subcommand_from workspaces; and __omniwmctl_prev_arg_is --fields' -a 'layout'
complete -c omniwmctl -f -n '__fish_seen_subcommand_from query; and __fish_seen_subcommand_from workspaces; and __omniwmctl_prev_arg_is --fields' -a 'number'
complete -c omniwmctl -f -n '__fish_seen_subcommand_from query; and __fish_seen_subcommand_from workspaces; and __omniwmctl_prev_arg_is --fields' -a 'raw-name'
complete -c omniwmctl -f -n '__fish_seen_subcommand_from query; and __fish_seen_subcommand_from workspaces; and __omniwmctl_prev_arg_is --fields' -a 'window-counts'
complete -c omniwmctl -f -n '__fish_seen_subcommand_from command' -a 'balance-sizes'
complete -c omniwmctl -f -n '__fish_seen_subcommand_from command' -a 'cycle-column-width'
complete -c omniwmctl -f -n '__fish_seen_subcommand_from command' -a 'focus'
complete -c omniwmctl -f -n '__fish_seen_subcommand_from command' -a 'focus-column'
complete -c omniwmctl -f -n '__fish_seen_subcommand_from command' -a 'focus-monitor'
complete -c omniwmctl -f -n '__fish_seen_subcommand_from command' -a 'move'
complete -c omniwmctl -f -n '__fish_seen_subcommand_from command' -a 'move-column'
complete -c omniwmctl -f -n '__fish_seen_subcommand_from command' -a 'move-column-to-workspace'
complete -c omniwmctl -f -n '__fish_seen_subcommand_from command' -a 'move-to-root'
complete -c omniwmctl -f -n '__fish_seen_subcommand_from command' -a 'move-to-workspace'
complete -c omniwmctl -f -n '__fish_seen_subcommand_from command' -a 'open-command-palette'
complete -c omniwmctl -f -n '__fish_seen_subcommand_from command' -a 'open-menu-anywhere'
complete -c omniwmctl -f -n '__fish_seen_subcommand_from command' -a 'preselect'
complete -c omniwmctl -f -n '__fish_seen_subcommand_from command' -a 'raise-all-floating-windows'
complete -c omniwmctl -f -n '__fish_seen_subcommand_from command' -a 'rescue-offscreen-windows'
complete -c omniwmctl -f -n '__fish_seen_subcommand_from command' -a 'resize'
complete -c omniwmctl -f -n '__fish_seen_subcommand_from command' -a 'scratchpad'
complete -c omniwmctl -f -n '__fish_seen_subcommand_from command' -a 'set-workspace-layout'
complete -c omniwmctl -f -n '__fish_seen_subcommand_from command' -a 'swap-split'
complete -c omniwmctl -f -n '__fish_seen_subcommand_from command' -a 'swap-workspace-with-monitor'
complete -c omniwmctl -f -n '__fish_seen_subcommand_from command' -a 'switch-workspace'
complete -c omniwmctl -f -n '__fish_seen_subcommand_from command' -a 'toggle-column-full-width'
complete -c omniwmctl -f -n '__fish_seen_subcommand_from command' -a 'toggle-column-tabbed'
complete -c omniwmctl -f -n '__fish_seen_subcommand_from command' -a 'toggle-focused-window-floating'
complete -c omniwmctl -f -n '__fish_seen_subcommand_from command' -a 'toggle-fullscreen'
complete -c omniwmctl -f -n '__fish_seen_subcommand_from command' -a 'toggle-hidden-bar'
complete -c omniwmctl -f -n '__fish_seen_subcommand_from command' -a 'toggle-native-fullscreen'
complete -c omniwmctl -f -n '__fish_seen_subcommand_from command' -a 'toggle-overview'
complete -c omniwmctl -f -n '__fish_seen_subcommand_from command' -a 'toggle-quake-terminal'
complete -c omniwmctl -f -n '__fish_seen_subcommand_from command' -a 'toggle-split'
complete -c omniwmctl -f -n '__fish_seen_subcommand_from command' -a 'toggle-workspace-bar'
complete -c omniwmctl -f -n '__fish_seen_subcommand_from command' -a 'toggle-workspace-layout'
complete -c omniwmctl -f -n '__fish_seen_subcommand_from command; and __fish_seen_subcommand_from cycle-column-width' -a 'backward'
complete -c omniwmctl -f -n '__fish_seen_subcommand_from command; and __fish_seen_subcommand_from cycle-column-width' -a 'forward'
complete -c omniwmctl -f -n '__fish_seen_subcommand_from command; and __fish_seen_subcommand_from focus' -a 'down'
complete -c omniwmctl -f -n '__fish_seen_subcommand_from command; and __fish_seen_subcommand_from focus' -a 'down-or-left'
complete -c omniwmctl -f -n '__fish_seen_subcommand_from command; and __fish_seen_subcommand_from focus' -a 'left'
complete -c omniwmctl -f -n '__fish_seen_subcommand_from command; and __fish_seen_subcommand_from focus' -a 'previous'
complete -c omniwmctl -f -n '__fish_seen_subcommand_from command; and __fish_seen_subcommand_from focus' -a 'right'
complete -c omniwmctl -f -n '__fish_seen_subcommand_from command; and __fish_seen_subcommand_from focus' -a 'up'
complete -c omniwmctl -f -n '__fish_seen_subcommand_from command; and __fish_seen_subcommand_from focus' -a 'up-or-right'
complete -c omniwmctl -f -n '__fish_seen_subcommand_from command; and __fish_seen_subcommand_from focus-column' -a 'first'
complete -c omniwmctl -f -n '__fish_seen_subcommand_from command; and __fish_seen_subcommand_from focus-column' -a 'last'
complete -c omniwmctl -f -n '__fish_seen_subcommand_from command; and __fish_seen_subcommand_from focus-monitor' -a 'last'
complete -c omniwmctl -f -n '__fish_seen_subcommand_from command; and __fish_seen_subcommand_from focus-monitor' -a 'next'
complete -c omniwmctl -f -n '__fish_seen_subcommand_from command; and __fish_seen_subcommand_from focus-monitor' -a 'prev'
complete -c omniwmctl -f -n '__fish_seen_subcommand_from command; and __fish_seen_subcommand_from focus-monitor' -a 'previous'
complete -c omniwmctl -f -n '__fish_seen_subcommand_from command; and __fish_seen_subcommand_from move' -a 'down'
complete -c omniwmctl -f -n '__fish_seen_subcommand_from command; and __fish_seen_subcommand_from move' -a 'left'
complete -c omniwmctl -f -n '__fish_seen_subcommand_from command; and __fish_seen_subcommand_from move' -a 'right'
complete -c omniwmctl -f -n '__fish_seen_subcommand_from command; and __fish_seen_subcommand_from move' -a 'up'
complete -c omniwmctl -f -n '__fish_seen_subcommand_from command; and __fish_seen_subcommand_from move-column' -a 'down'
complete -c omniwmctl -f -n '__fish_seen_subcommand_from command; and __fish_seen_subcommand_from move-column' -a 'left'
complete -c omniwmctl -f -n '__fish_seen_subcommand_from command; and __fish_seen_subcommand_from move-column' -a 'right'
complete -c omniwmctl -f -n '__fish_seen_subcommand_from command; and __fish_seen_subcommand_from move-column' -a 'up'
complete -c omniwmctl -f -n '__fish_seen_subcommand_from command; and __fish_seen_subcommand_from move-column-to-workspace' -a 'down'
complete -c omniwmctl -f -n '__fish_seen_subcommand_from command; and __fish_seen_subcommand_from move-column-to-workspace' -a 'up'
complete -c omniwmctl -f -n '__fish_seen_subcommand_from command; and __fish_seen_subcommand_from move-to-workspace' -a 'down'
complete -c omniwmctl -f -n '__fish_seen_subcommand_from command; and __fish_seen_subcommand_from move-to-workspace' -a 'on-monitor'
complete -c omniwmctl -f -n '__fish_seen_subcommand_from command; and __fish_seen_subcommand_from move-to-workspace' -a 'up'
complete -c omniwmctl -f -n '__fish_seen_subcommand_from command; and __fish_seen_subcommand_from preselect' -a 'clear'
complete -c omniwmctl -f -n '__fish_seen_subcommand_from command; and __fish_seen_subcommand_from preselect' -a 'down'
complete -c omniwmctl -f -n '__fish_seen_subcommand_from command; and __fish_seen_subcommand_from preselect' -a 'left'
complete -c omniwmctl -f -n '__fish_seen_subcommand_from command; and __fish_seen_subcommand_from preselect' -a 'right'
complete -c omniwmctl -f -n '__fish_seen_subcommand_from command; and __fish_seen_subcommand_from preselect' -a 'up'
complete -c omniwmctl -f -n '__fish_seen_subcommand_from command; and __fish_seen_subcommand_from resize' -a 'down'
complete -c omniwmctl -f -n '__fish_seen_subcommand_from command; and __fish_seen_subcommand_from resize' -a 'left'
complete -c omniwmctl -f -n '__fish_seen_subcommand_from command; and __fish_seen_subcommand_from resize' -a 'right'
complete -c omniwmctl -f -n '__fish_seen_subcommand_from command; and __fish_seen_subcommand_from resize' -a 'up'
complete -c omniwmctl -f -n '__fish_seen_subcommand_from command; and __fish_seen_subcommand_from scratchpad' -a 'assign'
complete -c omniwmctl -f -n '__fish_seen_subcommand_from command; and __fish_seen_subcommand_from scratchpad' -a 'toggle'
complete -c omniwmctl -f -n '__fish_seen_subcommand_from command; and __fish_seen_subcommand_from set-workspace-layout' -a 'default'
complete -c omniwmctl -f -n '__fish_seen_subcommand_from command; and __fish_seen_subcommand_from set-workspace-layout' -a 'dwindle'
complete -c omniwmctl -f -n '__fish_seen_subcommand_from command; and __fish_seen_subcommand_from set-workspace-layout' -a 'niri'
complete -c omniwmctl -f -n '__fish_seen_subcommand_from command; and __fish_seen_subcommand_from swap-workspace-with-monitor' -a 'down'
complete -c omniwmctl -f -n '__fish_seen_subcommand_from command; and __fish_seen_subcommand_from swap-workspace-with-monitor' -a 'left'
complete -c omniwmctl -f -n '__fish_seen_subcommand_from command; and __fish_seen_subcommand_from swap-workspace-with-monitor' -a 'right'
complete -c omniwmctl -f -n '__fish_seen_subcommand_from command; and __fish_seen_subcommand_from swap-workspace-with-monitor' -a 'up'
complete -c omniwmctl -f -n '__fish_seen_subcommand_from command; and __fish_seen_subcommand_from switch-workspace' -a 'anywhere'
complete -c omniwmctl -f -n '__fish_seen_subcommand_from command; and __fish_seen_subcommand_from switch-workspace' -a 'back'
complete -c omniwmctl -f -n '__fish_seen_subcommand_from command; and __fish_seen_subcommand_from switch-workspace' -a 'back-and-forth'
complete -c omniwmctl -f -n '__fish_seen_subcommand_from command; and __fish_seen_subcommand_from switch-workspace' -a 'next'
complete -c omniwmctl -f -n '__fish_seen_subcommand_from command; and __fish_seen_subcommand_from switch-workspace' -a 'prev'
complete -c omniwmctl -f -n '__fish_seen_subcommand_from command; and __fish_seen_subcommand_from switch-workspace' -a 'previous'
complete -c omniwmctl -f -n '__fish_seen_subcommand_from command; and __fish_seen_subcommand_from resize' -a 'grow'
complete -c omniwmctl -f -n '__fish_seen_subcommand_from command; and __fish_seen_subcommand_from resize' -a 'shrink'
complete -c omniwmctl -f -n '__fish_seen_subcommand_from command; and __fish_seen_subcommand_from move-to-workspace; and __fish_seen_subcommand_from on-monitor' -a 'down'
complete -c omniwmctl -f -n '__fish_seen_subcommand_from command; and __fish_seen_subcommand_from move-to-workspace; and __fish_seen_subcommand_from on-monitor' -a 'left'
complete -c omniwmctl -f -n '__fish_seen_subcommand_from command; and __fish_seen_subcommand_from move-to-workspace; and __fish_seen_subcommand_from on-monitor' -a 'right'
complete -c omniwmctl -f -n '__fish_seen_subcommand_from command; and __fish_seen_subcommand_from move-to-workspace; and __fish_seen_subcommand_from on-monitor' -a 'up'
complete -c omniwmctl -f -n '__fish_seen_subcommand_from rule' -a 'add'
complete -c omniwmctl -f -n '__fish_seen_subcommand_from rule' -a 'replace'
complete -c omniwmctl -f -n '__fish_seen_subcommand_from rule' -a 'remove'
complete -c omniwmctl -f -n '__fish_seen_subcommand_from rule' -a 'move'
complete -c omniwmctl -f -n '__fish_seen_subcommand_from rule' -a 'apply'
complete -c omniwmctl -f -n '__fish_seen_subcommand_from rule; and __fish_seen_subcommand_from apply' -a '--focused'
complete -c omniwmctl -f -n '__fish_seen_subcommand_from rule; and __fish_seen_subcommand_from apply' -a '--window'
complete -c omniwmctl -f -n '__fish_seen_subcommand_from rule; and __fish_seen_subcommand_from apply' -a '--pid'
complete -c omniwmctl -f -n '__fish_seen_subcommand_from subscribe' -a '--all'
complete -c omniwmctl -f -n '__fish_seen_subcommand_from subscribe' -a '--no-send-initial'
complete -c omniwmctl -f -n '__fish_seen_subcommand_from subscribe' -a 'active-workspace'
complete -c omniwmctl -f -n '__fish_seen_subcommand_from subscribe' -a 'display-changed'
complete -c omniwmctl -f -n '__fish_seen_subcommand_from subscribe' -a 'focus'
complete -c omniwmctl -f -n '__fish_seen_subcommand_from subscribe' -a 'focused-monitor'
complete -c omniwmctl -f -n '__fish_seen_subcommand_from subscribe' -a 'layout-changed'
complete -c omniwmctl -f -n '__fish_seen_subcommand_from subscribe' -a 'windows-changed'
complete -c omniwmctl -f -n '__fish_seen_subcommand_from subscribe' -a 'workspace-bar'
complete -c omniwmctl -f -n '__fish_seen_subcommand_from watch' -a '--all'
complete -c omniwmctl -f -n '__fish_seen_subcommand_from watch' -a '--exec'
complete -c omniwmctl -f -n '__fish_seen_subcommand_from watch' -a '--no-send-initial'
complete -c omniwmctl -f -n '__fish_seen_subcommand_from watch' -a 'active-workspace'
complete -c omniwmctl -f -n '__fish_seen_subcommand_from watch' -a 'display-changed'
complete -c omniwmctl -f -n '__fish_seen_subcommand_from watch' -a 'focus'
complete -c omniwmctl -f -n '__fish_seen_subcommand_from watch' -a 'focused-monitor'
complete -c omniwmctl -f -n '__fish_seen_subcommand_from watch' -a 'layout-changed'
complete -c omniwmctl -f -n '__fish_seen_subcommand_from watch' -a 'windows-changed'
complete -c omniwmctl -f -n '__fish_seen_subcommand_from watch' -a 'workspace-bar'
complete -c omniwmctl -f -n '__fish_seen_subcommand_from workspace' -a 'focus-name'
complete -c omniwmctl -f -n '__fish_seen_subcommand_from window' -a 'focus'
complete -c omniwmctl -f -n '__fish_seen_subcommand_from window' -a 'navigate'
complete -c omniwmctl -f -n '__fish_seen_subcommand_from window' -a 'summon-right'
complete -c omniwmctl -f -n '__fish_seen_subcommand_from completion' -a 'zsh'
complete -c omniwmctl -f -n '__fish_seen_subcommand_from completion' -a 'bash'
complete -c omniwmctl -f -n '__fish_seen_subcommand_from completion' -a 'fish'
